In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

def get_html(url, headers):
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        return response.content
    return None

def parse_jobs(html_data):
    soup = BeautifulSoup(html_data, 'html.parser')
    job_listings = soup.find_all('div', class_='truncated-text-fix')
    jobs_data = []

    for job in job_listings:
        title = job.find('h2')
        company = job.find(class_="d-inline-block mt-1 mb-0 ng-star-inserted")
        types = job.find(class_="mr-1 mb-0 ng-star-inserted")
        lieu = job.find(class_="mr-3 mb-1 cc-font-size-small")
        date = job.find(class_="mb-0")
        jobs_data.append({"Titre": title, "Company": company, "Type": types, "Lieu": lieu, "Publication": date})

    return jobs_data

def create_dataframe(jobs_data):
    df_jobs = pd.DataFrame(jobs_data)
    return df_jobs.iloc[::2]

def main():
    url = "https://www.meteojob.com/jobs/meteo?job=36692~ENTRY_LEVEL~INTERMEDIATE~SENIOR~EXPERT&location=2996944~30"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Accept-Language': 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7',
    }
    
    html_data = get_html(url, headers)
    if html_data:
        jobs_data = parse_jobs(html_data)
        df_jobs = create_dataframe(jobs_data)
        display(df_jobs)

main()

,Titre,Company,Type,Lieu,Publication
0,[Data scientist en alternance (H/F)],[OpenClassrooms],"[[], Alternance / Apprentissage , ]","[[[], Solaize (69) , ]]","[[[], Hier , [Nouveau], ]]"
2,[Data Controller Comptable H/F],[Talents AEC],"[[], CDI , ]","[[[], Lyon 09 (69) , ]]","[[[], Il y a 4 jours , [Nouveau], ]]"
4,[CHARGE D'ETUDES STATISTIQUES F/H],[ADEQUAT],"[[], Intérim , ]","[[[], Saint-Genis-Laval (69) , ]]","[[[], Il y a 3 jours , [Nouveau], ]]"
6,[Data Ingénieur Talend H/F],[Amiltone],"[[], CDI , ]","[[[], Lyon (69) , ]]","[[[], Hier , [Nouveau], ]]"
8,[Détecteur anti-sous-marin H/F],[MARINE NATIONALE],"[[], CDD , [- 10 ans], ]","[[[], Lyon (69) , ]]","[[[], Il y a 12 jours , ]]"
10,[Détecteur H/F],[MARINE NATIONALE],"[[], CDD , [- 10 ans], ]","[[[], Lyon (69) , ]]","[[[], Il y a 12 jours , ]]"
12,[Analyste traitant du renseignement H/F],[MARINE NATIONALE],"[[], CDD , [- 4 ans], ]","[[[], Lyon (69) , ]]","[[[], Il y a 12 jours , ]]"
14,[Détecteur et analyste des signaux électromagn...,[MARINE NATIONALE],"[[], CDD , [- 4 ans], ]","[[[], Lyon (69) , ]]","[[[], Il y a 12 jours , ]]"
16,[GESTIONNAIRE MASTER DATA (F/H)],[Randstad],"[[], Intérim , [- 6 mois], ]","[[[], Saint-Genis-Laval (69) , ]]","[[[], Il y a 7 jours , ]]"
18,[Alternant - Analyste de données (H/F)],[Prosol],"[[], Alternance / Apprentissage , [- 12 mois], ]","[[[], Corbas (69) , ]]","[[[], Il y a 12 jours , ]]"
20,[Data Scientist (h/f)],[LHH Recruitment Solutions],"[[], CDI , ]","[[[], Villeurbanne (69) , ]]","[[[], Il y a 13 jours , ]]"
22,[Data Ingénieur Talend H/F],[Amiltone],"[[], CDI , ]","[[[], Lyon (69) , ]]","[[[], Il y a 18 jours , ]]"
24,None,None,None,None,None
26,None,None,None,None,None